name: Build Gatsby site
# This should be treated as 'private' and only be called by on-<some-action>.yml workflows
# You cannot add any child workflows to this workflow.
on:
  workflow_call:
    inputs:
      ENVIRONMENT:
        required: true
        type: string
      UPLOAD_ARTIFACTS:
        required: true
        type: boolean
    secrets:
      CONTENT_BRANCH:
        required: true
      GOOGLE_GTM_ID:
        required: true
      ZENDESK_CHAT_KEY:
        required: true
      RECAPTCHA_KEY:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.ENVIRONMENT }}

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.5.0

      - name: Create env File
        env:
          RECAPTCHA_KEY: ${{ secrets.RECAPTCHA_KEY }}
        run: |
          touch .env.production
          echo GITHUB_RUN_ID=${{ github.run_id }} >> .env.production
          echo GITHUB_RUN_NUMBER=${{ github.run_number }} >> .env.production
          echo RECAPTCHA_KEY=${{ RECAPTCHA_KEY }} >> .env.production
          cat .env.production
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CONTENT_REPO: https://github.com/SSWConsulting/SSW.Website.Content
          CONTENT_BRANCH: ${{ secrets.CONTENT_BRANCH }}
          GOOGLE_GTM_ID: ${{ secrets.GOOGLE_GTM_ID }}

      # Upload build artifacts for deployment
      - name: Upload Artifacts
        if: ${{ inputs.UPLOAD_ARTIFACTS }}
        uses: actions/upload-artifact@v2
        with:
          name: gatsby-build
          path: public
          retention-days: 1
