# This is a basic workflow to help you get started with Actions
name: Tests - CodeAuditor

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - main
    branches-ignore:
      - release/*
    Schedule:
      - cron: "0 14 * * 0"

jobs:
  needs: deploy-to-staging

  codeauditor-test:
  runs-on: ubuntu-latest

  steps:
    - uses: actions/checkout@v2

    - name: Tests - CodeAuditor
      shell: pwsh
      run: Invoke-Expression ".\$GITHUB_WORKSPACE\.github\templates\test.ps1"
