# This is a basic workflow to help you get started with Actions
name: Tests - CodeAuditor

# Controls when the workflow will run
# TODO: Run this workflow after Production - Deploy Gatsby in future
on:
  workflow_run:
    workflows: [Staging - Deploy Gatsby]
    types:
      - completed

    Schedule:
      - cron: "0 14 * * 0"

jobs:
  codeauditor-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Tests - CodeAuditor
        shell: pwsh
        run: Invoke-Expression ".\$GITHUB_WORKSPACE\.github\templates\test.ps1"
