name: Build + Deploy to staging

on:
  push:
    branches:
      - main #on push to the master branch do the jobs below

jobs:
  build:
    name: Build and upload artifacts
    uses: SSWConsulting/SSW.Website/.github/workflows/build.yml
    with:
      ENVIRONMENT: staging
      UPLOAD_ARTIFACTS: true # Upload artifacts so it can deploy to staging
    secrets:
      CONTENT_BRANCH: ${{ secrets.CONTENT_BRANCH}}
      GOOGLE_GTM_ID: ${{ secrets.GOOGLE_GTM_ID}}
      ZENDESK_CHAT_KEY: ${{ secrets.ZENDESK_CHAT_KEY}}
      RECAPTCHA_KEY: ${{ secrets.RECAPTCHA_KEY}}

  deploy-to:
    name: Download artifacts and deploy to staging
    needs: build
    uses: SSWConsulting/SSW.Website/.github/workflows/deploy.yml@main
    with:
      ENVIRONMENT: staging
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}
