name: PR Build

on:
  pull_request:
  

jobs:
  build:
    name: Build
    environment: staging
    uses: ./.github/workflows/build.yml
    with:
      ENVIRONMENT: staging
    secrets:
      GOOGLE_GTM_ID: ${{ secrets.GOOGLE_GTM_ID}}
      ZENDESK_CHAT_KEY: ${{ secrets.ZENDESK_CHAT_KEY}}
      RECAPTCHA_KEY: ${{ secrets.RECAPTCHA_KEY}}