name: PR Build

on:
  pull_request:
  

jobs:
  build:
    name: Build
    uses: SSWConsulting/SSW.Website/.github/workflows/build.yml@main
    with:
      ENVIRONMENT: staging
    secrets:
      GOOGLE_GTM_ID: ${{ secrets.GOOGLE_GTM_ID}}
      ZENDESK_CHAT_KEY: ${{ secrets.ZENDESK_CHAT_KEY}}
      RECAPTCHA_KEY: ${{ secrets.RECAPTCHA_KEY}}