name: PR - Build

on:
  workflow_dispatch:

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2.5.0

      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build
        env:
          CONTENT_REPO: https://github.com/SSWConsulting/SSW.Website.Content
          CONTENT_BRANCH: main
