# This is a basic workflow to help you get started with Actions

name: Staging - Deploy Azure Resources

# Controls when the workflow will run
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Create Azure Deployment
    - name: Create Deployment Group
      uses: azure/CLI@v1
      with:
        inlineScript: |
          az deployment group create --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} --template-file ssw-website.bicep --parameters {appName=sta, tenantId=${{ secrets.AZURE_TENANT }}}

    # Log out of Azure
    - name: logout
      run: |
            az logout
      if: always()
