name: Staging - Deploy Gatsby

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  deploy-to-staging:
    uses: SSWConsulting/SSW.Website/.github/workflows/reuseable-build-and-deploy-gatsby.yml@main
    with:
      ENVIRONMENT: Staging
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}
      CONTENT_BRANCH: ${{ secrets.CONTENT_BRANCH }}
      GOOGLE_GTM_ID: ${{ secrets.GOOGLE_GTM_ID }}
      ZENDESK_CHAT_KEY: ${{ secrets.ZENDESK_CHAT_KEY }}
