# This is a basic workflow to help you get started with Actions
name: Staging - Deploy Gatsby Site

# Controls when the workflow will run
on:
 # TODO: add on push to main
  workflow_dispatch:
  workflow_call:

jobs:
  deploy-to-staging:
    uses: SSWConsulting/SSW.Website/.github/workflows/build-deploy-gatsby.yml@main
    with:
      ENVIRONMENT: Staging
    secrets:
      AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}
      AZURE_APP_NAME: ${{ secrets.AZURE_APP_NAME }}
      CONTENT_BRANCH: ${{ secrets.CONTENT_BRANCH }}