# This is a basic workflow to help you get started with Actions

name: Staging - Deploy Gatsby Site

# Controls when the workflow will run
on:
 # TODO: Replace with on push to main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build Gatsby Site
    environment: Staging
    steps:
    - uses: actions/checkout@v2

    # Install Node and install packages
    - name: Use Node.js
      uses: actions/setup-node@v2.5.0
      
    - name: Install dependencies
      run: | 
        npm install
        npm install -g gatsby-cli
    
    # Run gatsby build
    - name: Gatsby Build
      run: gatsby build
    
    # Upload build artifact
    - name: Upload Gatsby Build Artifacts
      uses: actions/upload-artifact@v2
      with:
       name: gatsby-build
       path: public
       retention-days: 7
        
  deploy:
    runs-on: ubuntu-latest
    needs: build
    name: Deploy Gatsby to Azure
    environment: Staging

    steps:
    - name: Download Gatsby Build
      uses: actions/download-artifact@v2
      with:
       name: gatsby-build
   
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Upload blob to Azure Blob Storage
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_NAME }} --auth-mode key -d '$web' -s .

    # Log out of Azure
    - name: logout
      run: |
            az logout
      if: always()
