# This is a basic workflow to help you get started with Actions

name: Staging - Deploy Gatsby Site

# Controls when the workflow will run
on:
 # TODO: Replace with on push to main
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    environment: Staging
    steps:
    - uses: actions/checkout@v2
    
    # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    # Install Node and install packages
    - name: Use Node.js
      uses: actions/setup-node@v2.5.0
      
    - name: Install dependencies
      run: | 
        npm install
        npm install -g gatsby-cli
    
    # Run gatsby build
    - name: Gatsby Build
      run: gatsby build
      
    # Upload blob to Azure Blob Storage
    - name: Upload to blob storage
      uses: azure/CLI@v1
      with:
        inlineScript: |
            az storage blob delete-batch --account-name ${{ secrets.AZURE_STORAGE_NAME }} -s "\$web" --auth-mode key
            az storage blob upload-batch --account-name ${{ secrets.AZURE_STORAGE_NAME }} --auth-mode key -d '$web' -s public
      
    # Log out of Azure
    - name: logout
      run: |
            az logout
      if: always()
